### ISSUE TITLE
Fim < inicio

### ISSUE THREAD

**Issue by jvopinho** [Victoreisdavid/gerador-de-tabuada#1]
É possivel colocar um "Fim" menor que o "Inicio", o que não gera nenhuma tabuada.
Para esse caso seria bom um alerta falando que o "Inicio" não pode ser maior que o "Fim"
![image](https://user-images.githubusercontent.com/74413554/157532619-c2cd2b8d-587c-4222-8157-7a3396d8ad7b.png)

**Comment by Victoreisdavid** [comment]
Adicionei um aviso para quando isso acontecer.
Obrigado pela contribuição!
